fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login
_google_login:
    path: /login/check-google

api_login:
    path: /api/login

app_api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
    prefix: api

app_web:
    resource: '@AppBundle/Controller/Web'
    type: annotation
