<?php

namespace AppBundle\Repository\AvantSimple;

/**
 * RedeemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedeemRepository extends \Doctrine\ORM\EntityRepository
{
}
